//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerceraEntrega
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENERGIAEntities : DbContext
    {
        public ENERGIAEntities()
            : base("name=ENERGIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbConsumoAgua> tbConsumoAguas { get; set; }
        public virtual DbSet<tbConsumoGa> tbConsumoGas { get; set; }
        public virtual DbSet<tbEnergiaConsumo> tbEnergiaConsumoes { get; set; }
        public virtual DbSet<tbUsuario> tbUsuarios { get; set; }
    }
}
