//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerceraEntrega
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEnergiaConsumo
    {
        public int idUsuario { get; set; }
        public int Cedula { get; set; }
        public int Periodo_consumo { get; set; }
        public int Meta_ahorro_energia { get; set; }
        public int Consumo_actual_energia { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
